<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Winpepper.History</RootNamespace>
    <AssemblyName>Winpepper.History</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Winpepper.Core\Winpepper.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="DiffPlex" />
  </ItemGroup>
</Project>
