<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Winpepper.Cleanup</RootNamespace>
    <AssemblyName>Winpepper.Cleanup</AssemblyName>
    <TargetFrameworks>net9.0;net9.0-windows10.0.19041.0</TargetFrameworks>
    <TargetFramework></TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Winpepper.Core\Winpepper.Core.csproj" />
    <ProjectReference Include="..\Winpepper.Corrections\Winpepper.Corrections.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">
    <PackageReference Include="LLamaSharp" />
    <PackageReference Include="LLamaSharp.Backend.Vulkan" />
  </ItemGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Winpepper.Cleanup.Tests" />
  </ItemGroup>
</Project>
