#!/usr/bin/env python3
"""Static structural checks for packaging/winpepper.wxs.

The WiX toolchain and Windows Installer are unavailable on Linux, so the MSI
cannot be built or ICE-validated here. This script enforces the invariants we
CAN verify statically for the per-user scope conversion:

  1. The file is well-formed XML.
  2. The package installs per-user (Scope="perUser") -> no UAC elevation.
  3. No component WRITES to HKLM (per-machine hive). Reads (RegistrySearch)
     from HKLM are allowed and need no elevation.
  4. The install tree roots at LocalAppDataFolder (per-user convention) and
     never at ProgramFiles64Folder (per-machine).
  5. Every ComponentRef / ComponentGroupRef resolves to a component/group
     defined in this file, except build-generated groups (HarvestedFiles).
  6. Every Component @Directory attribute resolves to a Directory or
     StandardDirectory Id defined in this file (or a well-known folder).

Exit code 0 = all checks pass; 1 = at least one failure (details printed).
"""
from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

WXS_PATH = Path(__file__).resolve().parent / "winpepper.wxs"

# ComponentGroups generated by the WiX build (Heat HarvestDirectory in
# Winpepper.Msi.wixproj), not defined in winpepper.wxs.
GENERATED_COMPONENT_GROUPS = {"HarvestedFiles"}

# Directory ids resolved by the Windows Installer itself.
WELL_KNOWN_DIRECTORY_IDS = {
    "LocalAppDataFolder",
    "ProgramFiles64Folder",
    "ProgramFilesFolder",
    "ProgramMenuFolder",
    "AppDataFolder",
    "TARGETDIR",
}


def localname(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def main() -> int:
    failures: list[str] = []

    # Check 1: well-formed XML.
    try:
        tree = ET.parse(WXS_PATH)
    except ET.ParseError as exc:
        print(f"FAIL: {WXS_PATH.name} is not well-formed XML: {exc}")
        return 1
    root = tree.getroot()

    by_name: dict[str, list[ET.Element]] = {}
    for e in root.iter():
        by_name.setdefault(localname(e.tag), []).append(e)

    # Check 2: per-user scope.
    scopes = [p.get("Scope") for p in by_name.get("Package", [])]
    if "perUser" not in scopes:
        failures.append(f"Package/@Scope must be 'perUser'; found {scopes}")

    # Check 3: no HKLM writes (RegistryValue). RegistrySearch reads are allowed.
    for rv in by_name.get("RegistryValue", []):
        if rv.get("Root") == "HKLM":
            failures.append(
                "RegistryValue writes to HKLM (needs elevation): "
                f"Key={rv.get('Key')} Name={rv.get('Name')}"
            )

    # Check 4: directory roots.
    std_ids = {d.get("Id") for d in by_name.get("StandardDirectory", [])}
    if "LocalAppDataFolder" not in std_ids:
        failures.append(
            "StandardDirectory 'LocalAppDataFolder' is required for per-user install"
        )
    if "ProgramFiles64Folder" in std_ids:
        failures.append(
            "StandardDirectory 'ProgramFiles64Folder' is per-machine; remove it"
        )

    defined_dir_ids = set(std_ids)
    for d in by_name.get("Directory", []):
        if d.get("Id"):
            defined_dir_ids.add(d.get("Id"))

    # Check 5: ref resolution.
    comp_ids = {c.get("Id") for c in by_name.get("Component", []) if c.get("Id")}
    for ref in by_name.get("ComponentRef", []):
        rid = ref.get("Id")
        if rid not in comp_ids:
            failures.append(f"ComponentRef Id='{rid}' has no matching Component")

    group_ids = {
        g.get("Id") for g in by_name.get("ComponentGroup", []) if g.get("Id")
    }
    for ref in by_name.get("ComponentGroupRef", []):
        rid = ref.get("Id")
        if rid not in group_ids and rid not in GENERATED_COMPONENT_GROUPS:
            failures.append(
                f"ComponentGroupRef Id='{rid}' has no matching ComponentGroup"
            )

    # Check 6: Component @Directory resolves.
    resolvable = defined_dir_ids | WELL_KNOWN_DIRECTORY_IDS
    for c in by_name.get("Component", []):
        d = c.get("Directory")
        if d and d not in resolvable:
            failures.append(
                f"Component Id='{c.get('Id')}' Directory='{d}' does not resolve"
            )

    if failures:
        print(f"FAIL: {len(failures)} problem(s) in {WXS_PATH.name}:")
        for f in failures:
            print(f"  - {f}")
        return 1

    print(f"PASS: {WXS_PATH.name} passes all per-user static checks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
