<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Winpepper.Core\Winpepper.Core.csproj" />
    <ProjectReference Include="..\..\src\Winpepper.Corrections\Winpepper.Corrections.csproj" />
    <ProjectReference Include="..\..\src\Winpepper.Models\Winpepper.Models.csproj" />
    <ProjectReference Include="..\..\src\Winpepper.Asr\Winpepper.Asr.csproj" />
    <ProjectReference Include="..\..\src\Winpepper.Platform\Winpepper.Platform.csproj" />
    <ProjectReference Include="..\..\src\Winpepper.Cleanup\Winpepper.Cleanup.csproj" />
  </ItemGroup>
</Project>
